#SUPER DATASETS and CLASSES

fooddetection:
  - porkbasil

truck:
  - lpr_truck

VOC_CLASSES:
  - aeroplane
  - bicycle
  - bird
  - boat
  - bottle
  - bus
  - car
  - cat
  - chair
  - cow
  - diningtable
  - dog
  - horse
  - motorbike
  - person
  - pottedplant
  - sheep
  - sofa
  - train
  - tvmonitor
